[package]
name = "gml_to_graphml"
version = "0.1.0"
authors = ["Maxime Jacques <maxime@mims.ai>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
graph-io-gml = "0.3.0"
nom = "*"
quick-xml = "*"
itertools = "*"
serde_json = "*"
#petgraph-graphml = "2.0.1"
#petgraph = "0.5.1"